#!/usr/bin/env python3
"""Generate the embedded allowlist from ../mapping.json. No third-party packages."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def render():
    mapping = json.loads((ROOT.parent / "mapping.json").read_text())
    rows = mapping["components"]
    lines = ["// Generated by generate_mapping.py; edit ../mapping.json instead.",
             "#pragma once", "#include <stdint.h>", "namespace nanoels {",
             "struct Field { const char* name; uint8_t page, id; };",
             "static const Field kFields[] = {"]
    for row in rows:
        if row["live_text"]:
            lines.append('    {%s, %d, %d},' %
                         (json.dumps(row["name"]), row["page"], row["id"]))
    lines += ["};", "struct Touch { const char* topic; uint8_t page, id; };",
              "static const Touch kTouches[] = {"]
    for row in rows:
        if row["action"] and row["nextion_page"] is not None:
            lines.append('    {%s, %d, %d},' %
                         (json.dumps(row["openhasp"]), row["nextion_page"],
                          row["nextion_component_id"]))
    lines += ["};", "struct Page { uint8_t nextion, openhasp; };",
              "static const Page kPages[] = {"]
    for before, after in mapping["pages"].items():
        lines.append("    {%d, %d}," % (int(before), after))
    lines += ["};", "} // namespace nanoels", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "nanoels_mapping.h"
    expected = render()
    if args.check:
        if not target.exists() or target.read_text() != expected:
            parser.exit(1, "Mapping is stale: run generate_mapping.py\n")
    else:
        target.write_text(expected)
